# Generated by Django 5.2.4 on 2025-08-01 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend_id', models.CharField(max_length=100, unique=True)),
                ('chat_id', models.BigIntegerField()),
                ('user_id', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=40, unique=True)),
                ('members', models.TextField()),
                ('group_name', models.CharField(max_length=100)),
                ('group_description', models.TextField()),
                ('group_settings', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=30, unique=True)),
                ('content', models.TextField()),
                ('target', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('chat_id', models.CharField(max_length=255)),
                ('socials', models.JSONField()),
                ('friends', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='telegramApp.friends', to_field='friend_id')),
                ('groups', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='telegramApp.groups', to_field='group_id')),
                ('posts', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='telegramApp.posts', to_field='post_id')),
            ],
        ),
    ]
