# Generated by Django 5.2.4 on 2025-08-08 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegramApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramusers',
            name='friends',
        ),
        migrations.RemoveField(
            model_name='telegramusers',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='telegramusers',
            name='posts',
        ),
        migrations.AddField(
            model_name='friends',
            name='telegram',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='telegramApp.telegramusers', to_field='chat_id'),
        ),
        migrations.AddField(
            model_name='groups',
            name='telegram',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='telegramApp.telegramusers', to_field='chat_id'),
        ),
        migrations.AddField(
            model_name='posts',
            name='telegram',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='telegramApp.telegramusers', to_field='chat_id'),
        ),
        migrations.AlterField(
            model_name='telegramusers',
            name='chat_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
