# Generated by Django 5.2.4 on 2025-08-22 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telegramApp", "0003_products"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="user",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.RESTRICT,
                to="telegramApp.telegramusers",
                to_field="chat_id",
            ),
            preserve_default=False,
        ),
    ]
