# Generated by Django 5.2.4 on 2025-08-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telegramApp", "0004_products_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramusers",
            name="location",
            field=models.CharField(default=""),
        ),
        migrations.AddField(
            model_name="telegramusers",
            name="phone_number",
            field=models.CharField(default="", max_length=30),
        ),
        migrations.AddField(
            model_name="telegramusers",
            name="username",
            field=models.CharField(default="", max_length=255),
        ),
    ]
