# Generated by Django 5.2.4 on 2025-08-25 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "telegramApp",
            "0005_telegramusers_location_telegramusers_phone_number_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="telegramusers",
            name="first_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="telegramusers",
            name="last_name",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
