# Generated by Django 5.2.4 on 2025-08-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telegramApp", "0006_alter_telegramusers_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="telegramusers",
            name="socials",
            field=models.JSONField(null=True),
        ),
    ]
