# Generated by Django 5.2.4 on 2025-08-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telegramApp", "0007_alter_telegramusers_socials"),
    ]

    operations = [
        migrations.AlterField(
            model_name="telegramusers",
            name="location",
            field=models.CharField(default="", null=True),
        ),
        migrations.AlterField(
            model_name="telegramusers",
            name="phone_number",
            field=models.CharField(default="", max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="telegramusers",
            name="username",
            field=models.CharField(default="", max_length=255, null=True),
        ),
    ]
