# Generated by Django 5.2.4 on 2025-08-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telegramApp", "0008_alter_telegramusers_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="image",
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
