# Generated by Django 5.2.4 on 2025-08-27 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telegramApp", "0009_products_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramusers",
            name="balance",
            field=models.FloatField(default=0.0),
        ),
    ]
