# Generated by Django 5.2.4 on 2025-08-27 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telegramApp", "0010_telegramusers_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramusers",
            name="referee",
            field=models.BigIntegerField(default=0),
        ),
    ]
