# Generated by Django 5.2.4 on 2025-08-27 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telegramApp", "0011_telegramusers_referee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groups",
            name="group_settings",
            field=models.TextField(default="[]"),
        ),
        migrations.AlterField(
            model_name="groups",
            name="members",
            field=models.TextField(default="[]"),
        ),
    ]
