# Generated by Django 5.2.6 on 2025-09-09 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegramApp', '0013_topup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sharedpost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=30, unique=True)),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('shared_by', models.DateTimeField(auto_now_add=True)),
                ('original_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='telegramApp.posts')),
            ],
        ),
    ]
