# Generated by Django 5.2.4 on 2025-09-15 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telegramApp", "0014_sharedpost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topup",
            name="chat_id",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="topup",
            name="currency",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="topup",
            name="email",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="topup",
            name="name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="topup",
            name="payload",
            field=models.JSONField(unique=True),
        ),
        migrations.AlterField(
            model_name="topup",
            name="shipping_address",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="topup",
            name="title",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
