# Generated by Django 5.2.4 on 2025-09-17 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("telegramApp", "0015_alter_topup_chat_id_alter_topup_currency_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="posts",
            name="post_id",
        ),
    ]
